export const CLEAR_ITEMS = "CLEAR_ITEMS"
export const DEL = "REMOVE"
export const INC = "INC"
export const DEC = "DEC"
export const GET_TOTALS = "GET_TOTALS"
export const DISPLAY_ITEM = "DISPLAY_ITEM"